# Generated by Django 5.1.1 on 2024-10-29 22:48

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spycat',
            name='breed',
            field=models.CharField(max_length=50, validators=[cats.models.validate_cat_breed]),
        ),
    ]
